GET http://localhost:8800/api/users/65538cda5aff1e1cd9832eed

### REGISTER
POST http://localhost:8800/api/auth/register 
Content-Type: application/json

{
        "username":"nick",
        "email":"nick@gmail.com",
        "password" : "12345678"
}

### Login
POST http://localhost:8800/api/auth/login 
Content-Type: application/json

{
        "email":"nicky@gmail.com",
        "password" : "123456789"
}

###

DELETE http://localhost:3001/todos/delete/65228c60d448306a184decdb

### PUT http://localhost:3001/recipes/savedRecipes/ids/652393eb3e41808a37dd5745


###
PUT  http://localhost:8800/api/users/6553831e0a72c7edfc33748b
Content-Type: application/json

{
        "desc":"hey its my updated description!",
        "userId":"6553831e0a72c7edfc33748b",
        "password":"123456789"
}

###
DELETE   http://localhost:8800/api/users/6553831e0a72c7edfc33748b
Content-Type: application/json

{
        "userId":"6553831e0a72c7edfc33748b"
}

### follow

PUT  http://localhost:8800/api/users/65539f76d3216363997e7d84/follow
Content-Type: application/json

{
        "userId":"65538cda5aff1e1cd9832eed"
}

### unfollow

PUT  http://localhost:8800/api/users/65539f76d3216363997e7d84/unfollow
Content-Type: application/json

{
        "userId":"65538cda5aff1e1cd9832eed"
}

### post
POST http://localhost:8800/api/posts
Content-Type: application/json

{
        "userId":"65539f76d3216363997e7d84",
        "desc" : "first Post attempt from nick",
        "img":"nick.png"
}

### update post
PUT http://localhost:8800/api/posts/6553ceaec4496f314cb21b66
Content-Type: application/json

{
        "userId":"65539f76d3216363997e7d84",
        "desc" : "second Post attempt from nick",
        "img":"nick.png"
}